from pydantic_ai import Agent
from models.debate_model import DebateVerdict

judge_agent = Agent(
    model="openai:gpt-4o-mini",
    result_type=DebateVerdict,
    system_prompt=(
        "You are an objective Judge Agent in a multi-agent debate system.\n"
        "Your task is to review the debate history, which includes:\n"
        "1. The debate topic\n"
        "2. Factual evidence collected by the Researcher\n"
        "3. The argument in favor of the topic (PRO) generated by the Optimist\n"
        "4. The counterargument (CON) generated by the Skeptic\n\n"
        "Evaluate the quality of both arguments based on logical consistency, depth of reasoning, "
        "and how effectively they utilized the provided research evidence.\n"
        "Declare a winning stance (PRO, CON, or NEUTRAL if it is a tie).\n"
        "Provide a clear reasoning and a summary of your verdict. "
        "Strictly adhere to the DebateVerdict schema."
    )
)
